[options]
addons_path = /mnt/addons_library
data_dir = /var/lib/odoo
proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$gJCy9t47p/Q.JwRgLGXMeQ$COOK.58zhdSfekQW.O4jXPKo0o.iK1IX8bSEnAxHjteFbpXCaFAe/O.9A8Pf3y0rNiIEtCEudVoKGk/w4fAP0Q

